### ISSUE TITLE
How to include external libraries without having umd.js file

### ISSUE THREAD

**Issue by Rajan-corient** [toni-rmc/laravel-angular-integration#3]
Hi Toni,

Thanks for this new release....we'll definitely going to use this...

Is it possible to use third party library if there is no umd.js file present. If the answer is no then can you guide us how create umd.js for every external library on npm install . 

I have some of these libraries which are not having any umd.js file on npm install.....

--> ng2-slider-component.
--> ng2-datetime.

Thanks & Regard,
Rajan G

**Comment by toni-rmc** [comment]
Those are bundled using Webpack or something else.
They don't necessarily have end with `umd.js`.

I have taken a look at `ng2-slider-component` and yes they have bundled files of course, they just do not end with `umd.js` and they don't have to.

Try this entry:

`'ng2-slider-component': 'npm:ng2-slider-component/ng2-slider.component.system.js',`

**Comment by Rajan-corient** [comment]
Hi Toni,
Thanks for the reply

I tried this entry:

'ng2-slider-component': 'npm:ng2-slider-component/ng2-slider.component.system.js',

in app1/config.json but not getting the result  and neither getting any error on npm run ng-compile

I am using your Previous release not that update one.
can you please guide us how to inlcude these slider resources..... 

ng2-nouislider,
ng2-slider-component 


Thanks & Regard,
Rajan G

**Comment by toni-rmc** [comment]
If you are not using latest release than go into `node_modules` and copy the entire folder `ng2-slider-component` into `public/Ng`.

**Comment by Rajan-corient** [comment]
Thank you for the reply...

yes i did all..... just like we included angular2-multiselect-dropdown i in previous version and still i am unable to include this range-slider.

Thanks & Regard,
Rajan G

**Comment by toni-rmc** [comment]
Send me your files concerning that slider.

**Comment by Rajan-corient** [comment]
here is the concerning files


this is the result what i am getting...
![image](https://user-images.githubusercontent.com/31067215/29618459-d7de924c-8835-11e7-8552-2bef072bbb65.png)

and cmd also not showing any error 
![image](https://user-images.githubusercontent.com/31067215/29618967-5664f11e-8837-11e7-98f4-e535cec48609.png)

**Comment by Rajan-corient** [comment]
please find the concerning file if have'nt included by....

[app.component.txt](https://github.com/toni-rmc/laravel-angular-integration/files/1245685/app.component.txt)
[app.module.txt](https://github.com/toni-rmc/laravel-angular-integration/files/1245686/app.module.txt)
[app1.config.txt](https://github.com/toni-rmc/laravel-angular-integration/files/1245687/app1.config.txt)
[dashboard.component.txt](https://github.com/toni-rmc/laravel-angular-integration/files/1245688/dashboard.component.txt)


Thanks & Regard,
Rajan G

**Comment by toni-rmc** [comment]
I see you are not importing this module in the code.
In the future you should read documentation about library you want to integrate and find examples on line how to import library's modules and/or components in the code and what entries to make in SystemJS config file for that particular library.

`ng2-slider-component` has to work together with `ng2-slideable-directive` and `ng2-styled-directive`.
So locate folders `ng2-slideable-directive` and `ng2-styled-directive`  in `node_modules ` and copy them also in `public/Ng`.

After that in `app.module.ts` import them and declare in declarations array.

    // All 3 are needed for slider to work!
    import { Ng2StyledDirective } from 'ng2-styled-directive/ng2-styled.directive';
    import { SlideAbleDirective } from 'ng2-slideable-directive/slideable.directive';
    import { Ng2SliderComponent } from 'ng2-slider-component/ng2-slider.component';

    @NgModule({
        imports:      [
         ...
        ],

        declarations: [ 
           ...,
           Ng2StyledDirective,
           SlideAbleDirective,
           Ng2SliderComponent,
           ...
        ],
        bootstrap:    [ AppComponent ]
    })
    export class AppModule {}

After that in `app1.config.js` according to documentation you should make entries in `map` and `packages` sections.
Here is my config file, copy relevant entries from there

[app1.config.txt](https://github.com/toni-rmc/laravel-angular-integration/files/1247955/app1.config.txt)

Unfortunately since this library has some sort of a bug you will have to open `public/Ng/ng2-styled-directive/ng2-styled.directive.js` and locate line `#26`.

In `ng2-styled.directive.js` change this line at `#26` from this

`var component = this._view._element.component;`

to this

`var component = this._view.injector.view.context;`

Run `npm run ng-compile` and if you haven't make any errors elsewhere in your code it should work.
Here is the proof that it does:

![test](https://user-images.githubusercontent.com/1151177/29654026-d522b580-88ab-11e7-8178-31afd1ab9172.jpg)

**Comment by Rajan-corient** [comment]
Hi Toni,
Thank you for helping me with that....... now its working properly

please find the screenshot for the same...

![demo](https://user-images.githubusercontent.com/31067215/29671244-a1b2d1d4-8906-11e7-9b19-a3adec372099.png)


Thanks & Regard,
Rajan G
